In [14]:
#Naive Baines
import pandas as pd
from sklearn.preprocessing import StandardScaler
import sklearn
sc = StandardScaler()

In [15]:
df = pd.read_csv("df1.csv", index_col=0)
df

,subject,HR,sedentary mins,minutesAsleep,minutesAwake,deep_sleep_in_minutes,timeInBed,restlessness,stepsToday,very active mins,Flare
1,1,59.207012,709,378,52,36,430,0.078978,13118,56,False
2,1,62.188856,648,378,44,38,422,0.093491,14312,45,False
3,1,60.898110,760,361,38,37,399,0.064851,10970,28,False
4,1,56.284816,737,326,36,26,362,0.093185,16186,56,True
5,1,62.240648,849,341,23,65,364,0.064472,8189,11,False
...,...,...,...,...,...,...,...,...,...,...,...
151,1,57.769808,771,415,44,54,459,0.058306,7357,42,False
152,1,57.469693,821,307,38,59,345,0.096961,11532,65,False
153,1,60.046281,679,354,48,5,402,0.087126,16448,83,False
154,1,58.152992,840,349,65,55,474,0.056962,6698,22,False
155,1,58.367625,842,386,37,34,423,0.136473,4761,8,False

In [16]:
print(df.shape)
df.describe().transpose()

(154, 11)

,count,mean,std,min,25%,50%,75%,max
subject,154.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
HR,154.0,59.377883,2.374255,54.225121,57.845638,59.133633,60.895584,66.854347
sedentary mins,154.0,716.149351,106.469535,420.000000,647.250000,729.000000,797.000000,947.000000
minutesAsleep,154.0,354.792208,47.958952,190.000000,325.250000,349.000000,382.000000,510.000000
minutesAwake,154.0,43.487013,9.317379,23.000000,38.000000,42.000000,50.000000,69.000000
deep_sleep_in_minutes,154.0,39.194805,17.649854,0.000000,28.000000,38.000000,51.500000,93.000000
timeInBed,154.0,398.668831,52.740833,213.000000,364.000000,392.500000,427.750000,560.000000
restlessness,154.0,0.087275,0.030111,0.039437,0.065727,0.081330,0.101530,0.199021
stepsToday,154.0,12640.870130,4062.976125,4749.000000,9981.750000,12229.000000,15337.250000,24846.000000
very active mins,154.0,48.642857,32.048713,0.000000,24.250000,40.500000,69.250000,178.000000

In [17]:
target_column = ['Flare'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
subject,154.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.0
HR,154.0,0.888168,0.035514,0.811093,0.865249,0.884514,0.910869,1.0
sedentary mins,154.0,0.756230,0.112428,0.443506,0.683474,0.769799,0.841605,1.0
minutesAsleep,154.0,0.695671,0.094037,0.372549,0.637745,0.684314,0.749020,1.0
minutesAwake,154.0,0.630247,0.135034,0.333333,0.550725,0.608696,0.724638,1.0
deep_sleep_in_minutes,154.0,0.421450,0.189783,0.000000,0.301075,0.408602,0.553763,1.0
timeInBed,154.0,0.711909,0.094180,0.380357,0.650000,0.700893,0.763839,1.0
restlessness,154.0,0.438521,0.151296,0.198153,0.330254,0.408651,0.510146,1.0
stepsToday,154.0,0.508769,0.163526,0.191137,0.401745,0.492192,0.617293,1.0
very active mins,154.0,0.273274,0.180049,0.000000,0.136236,0.227528,0.389045,1.0

In [18]:
X = df[predictors].values
y = df[target_column].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)

print(X_train.shape); print(X_test.shape)

(107, 10)
(47, 10)

In [19]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [20]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train.ravel())

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [22]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)

In [24]:
print(ac)

0.5806451612903226

In [25]:
print(cm)

[[16  7]
 [ 6  2]]

In [26]:
print(cr)

              precision    recall  f1-score   support

       False       0.73      0.70      0.71        23
        True       0.22      0.25      0.24         8

    accuracy                           0.58        31
   macro avg       0.47      0.47      0.47        31
weighted avg       0.60      0.58      0.59        31